/**
 * Generates src/lib/source.ts from the real firmware files so the diff viewer
 * can never drift from what is actually committed in firmware/.
 * Run: node scripts/gen-source.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const firmware = join(here, "..", "..", "firmware");

// Strip one trailing newline so line counts shown on the page match what an
// editor reports, rather than counting the empty string after the last \n.
const read = (f) => readFileSync(join(firmware, f), "utf8").replace(/\n$/, "");

const ino = read("smart_led.ino");
const cpp = read("smart_led.cpp");

const out = `// GENERATED by scripts/gen-source.mjs. Do not edit by hand.
// Source of truth: firmware/smart_led.ino and firmware/smart_led.cpp

export const INO_SOURCE = ${JSON.stringify(ino)};

export const CPP_SOURCE = ${JSON.stringify(cpp)};

export const INO_LINES = INO_SOURCE.split("\\n");
export const CPP_LINES = CPP_SOURCE.split("\\n");
`;

mkdirSync(join(here, "..", "src", "lib"), { recursive: true });
writeFileSync(join(here, "..", "src", "lib", "source.ts"), out);

console.log(
  `wrote source.ts: ino ${ino.split("\n").length} lines, cpp ${cpp.split("\n").length} lines`,
);
