"use client";

import Image from "next/image";
import { BOARDS, MAP_BOUNDS, portComparison } from "@/lib/firmware";
import Section from "./Section";

/**
 * The loops that ship in the repository's README.
 *
 * These are not screen recordings. The build machine has no browser, so every
 * frame is drawn by scripts/gen-media.mjs, which imports the same firmware port
 * this page runs and steps loop() at 1ms resolution. That is the reason the
 * numbers burned into the GIFs match the numbers above them: they come out of
 * one implementation, not two.
 */

const CLIPS = [
  {
    src: "/media/bench.gif",
    file: "docs/media/bench.gif",
    title: "The bench",
    caption:
      "A scripted hand turns the trimmer and taps the button once. The trace underneath measures its own period off the recorded pin edges, so when the knob holds still the measured figure lands on the computed one.",
  },
  {
    src: "/media/port-lab.gif",
    file: "docs/media/port-lab.gif",
    title: "The port lab",
    caption:
      "One knob, two board profiles, the sketch's map() call left exactly as written. The Uno curve stops at the documented ceiling. The ESP32 curve keeps going.",
  },
  {
    src: "/media/loop-blocking.gif",
    file: "docs/media/loop-blocking.gif",
    title: "delay(50), in the act",
    caption:
      "Slowed four times so a 50ms stall is visible at all. The blink really is non-blocking. The debounce sitting three lines above it is not.",
  },
];

export default function Media() {
  const esp = portComparison(100, BOARDS.esp32);

  return (
    <Section
      id="media"
      eyebrow="Generated, not recorded"
      title="The same code drew these"
      lede="The repository ships three loops in its README. They were not captured off a screen, because the machine that builds this site has no browser on it. A script imports the firmware port you have been driving all the way down this page, steps loop() a millisecond at a time, and draws the frames."
    >
      <div className="grid gap-4 lg:grid-cols-3">
        {CLIPS.map((clip) => (
          <figure
            key={clip.src}
            className="border-edge bg-panel flex flex-col overflow-hidden rounded-xl border"
          >
            <Image
              src={clip.src}
              alt={clip.caption}
              width={760}
              height={420}
              unoptimized
              className="border-edge w-full border-b"
            />
            <figcaption className="flex flex-1 flex-col p-4">
              <h3 className="font-mono text-sm">{clip.title}</h3>
              <p className="text-ink-dim mt-2 flex-1 text-[13px] leading-relaxed">
                {clip.caption}
              </p>
              <code className="text-ink-faint mt-3 font-mono text-[10px]">
                {clip.file}
              </code>
            </figcaption>
          </figure>
        ))}
      </div>

      <div className="border-edge bg-panel mt-4 rounded-xl border p-5">
        <h3 className="font-mono text-sm">Why bother</h3>
        <p className="text-ink-dim mt-2 max-w-3xl text-[13px] leading-relaxed">
          A README screenshot goes stale the moment the code under it changes,
          and nobody notices, because a picture cannot fail a build. These are
          regenerated by{" "}
          <code className="text-trace font-mono text-[12px]">
            npm run media
          </code>{" "}
          from{" "}
          <code className="text-trace font-mono text-[12px]">
            src/lib/firmware.ts
          </code>
          . Change the sketch, rerun it, and the pictures move with the code.
          The{" "}
          <span className="text-alarm font-mono">{esp.actual}ms</span> in the
          port lab clip is computed at draw time from the same function that
          computes the{" "}
          <span className="text-ok font-mono">{MAP_BOUNDS.outMax}ms</span>{" "}
          ceiling, not typed into a caption.
        </p>
      </div>
    </Section>
  );
}
